# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lutherus.io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lutheurs.io
  template:
    metadata:
      labels:
        app: myblog
    spec:
      containers:
        - name: lutherus.io
          image: hugo:latest
          ports:
            - containerPort: 80
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: lutehrus.io
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: www.lutherus.io  # Replace with your own domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lutherus.io
                port:
                  number: 80
